### PR TITLE
Properly handle SIGTERM and other kernel events

### LINKED ISSUE #7198: Zigbee2Mqtt runned into Docker doesn't handle well SIGTERM
## What happened

When you run docker image `koenkk/zigbee2mqtt` with option `--restart always` and zigbee2mqtt fails (for example, unplug the USB key), the container is not automatically restarted.

I think it's link to the fact that CMD in Dockerfile is `npm start` and not `node index.js`. Because of that, PID 1 process is **npm** and not **node**.

When node fails, SIGTERM signals is not handle well by npm, so process is not killed the good way.

See https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/ (chapter 5)

```
pi@gladys:~ $ docker exec 4a8e754199c7  ps fax
PID   USER     TIME  COMMAND
    1 root      0:01 {node} npm
   24 root      0:07 node index.js
   45 root      0:00 ps fax
```

## What did you expect to happen

Docker must detect container is stopped and restart container. It's not the case.

## How to reproduce it (minimal and precise)

- Launch docker
```
docker run \
-it \
-v $(pwd)/data:/app/data \
--device=/dev/ttyACM0 \
-e TZ=Europe/Paris \
-v /run/udev:/run/udev:ro \
--privileged=true \
koenkk/zigbee2mqtt
```

- Unplug USB device
- Check container status

## Debug info
Zigbee2MQTT version: 1.18.2
Adapter hardware: CC2531
Adapter firmware version: 3.2.6

### PR DESCRIPTION
**Pull request by ssiergl**
see

https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals

### CODE REVIEW

**Comment by ssiergl** [comment]
completely untested....but should work

File: docker/docker-run.sh [hunk 1]
```diff
@@ -14,4 +14,6 @@ if [ ! -f "$DATA/configuration.yaml" ]; then
     cp /app/configuration.yaml "$DATA/configuration.yaml"
 fi
 
-exec "$@"
+exec node index.js
+
+exit 1
```
Comment (Koenkk) [inline docker/docker-run.sh:19]: Why is there `exit 1` here, does it mean it will always exit with code 1? I would expect that the exit code from `node index.js` is used instead.

Comment (ssiergl) [reply docker/docker-run.sh:19]: No should not.
tini is running with PID1
tini is spawning the process to be controlled which is `docker-run.sh`
`docker-run.sh` will execute the config stuff and hold on the forground process `node`
Well node does not handle exit values that well.....basically the exit 1 will be called if for whatever reason the node process stopped. Even if it was an expected exit which is not to be expected on zigbee2mqtt.

But we need to test ist. Did not have time to compile an image yesterday...will try to do this evening. High workload at the moment :D

Comment (ssiergl) [reply docker/docker-run.sh:19]: But yeah basically it is not needed to achieve our goal...more or less another layer to be sure the container restarts

Comment (Koenkk) [reply docker/docker-run.sh:19]: Good, let me know your results.

**Comment by ssiergl** [comment]
well...did some testing.

Basically it is way better now. There was another issue that SIGINT SIGTERM was not called (index.js line 57-58 => `handleQuit` => `controller.stop` => process will exit with code) due that the signal was never processed by node. With tini the signal exchange between docker and node does work as expected in both directions. Tested it with different conditions.

Nevertheless the original issue that docker refuses to restart the container persist although all signal handling is correct now:

Looking at docker events when removing zigbee USB stick:

```
2021-04-28T19:43:34.768756749Z container die fa5b1aa20b8057e210e135a32b06ecf22f02088e9ea4fe112fb69ee967d699e8 (com.docker.compose.config-hash=0f30598d0cbb93079a8356f3ebebc8802b54c1474d56b78fdf68a05b9e221634, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=zigbee2mqtt, com.docker.compose.project.config_files=docker-compose.yml, com.docker.compose.project.working_dir=/opt/docker/zigbee2mqtt, com.docker.compose.service=app, com.docker.compose.version=1.28.6, exitCode=1, image=444a91c00413, name=zigbee2mqtt_app)
```

all conditions met to restart the container. Right now no idea why not.

Still imo this commit should be merged to get a proper signal handling for all other cases.

PID process hierarchy with this patch:

image

Other way would be to use s6-overlay or supervisor.....IMHO both overkill for this task. Still not sure if the restart problem is a docker and or platform problem right now. Looking at the logs zigbee2mqtt image is doing everything as needed now.

**Comment by Koenkk** [comment]
I also don't understand why docker isn't restarting the container, anyway this is an improvement. Thanks for looking into this!

**Comment by ssiergl** [comment]
> I also don't understand why docker isn't restarting the container, anyway this is an improvement. Thanks for looking into this!

Will try to debug it this weekend and spin up the container on some production environments where I know that the signal handling is running for sure.

**Comment by ssiergl** [comment]
@Koenkk

I know why :/

Not sure if it is intended or a docker bug.

Did the following:

added sleep to `index.js`

```
function sleep(time) {
    return new Promise((resolve) => setTimeout(resolve, time));
}

sleep(60000).then(() => {
    start();
});
```

and to be sure it is not a whatever strange callback issue in `lib/controller.js`

```
    async start() {
        this.state.start();
        logger.logOutput();

        const info = await utils.getZigbee2mqttVersion();
        logger.info(`Starting Zigbee2MQTT version ${info.version} (commit #${info.commitHash})`);

        // Start zigbee
        try {
            this.exitCallback(1);
            
.....
```

So if you spin up the container all will work as expected.....after 60s `this.exitCallback(1);` is called, container dies with exit code 1 and docker immediately restarts the container.

Well.....just do the same again and simply remove the docker `device` (in this case our USB stick) during the 60s timeout......docker will not restart the container anymore. 

Conclusion: docker is stopping the restart behaviour if a mounted device is removed :/

Good news...any other zigbee2mqtt crash will restart the container 🌵

**Comment by cicoub13** [comment]
Thanks for all the tests and feedbacks 🙏 
I've found this here https://docs.docker.com/config/containers/start-containers-automatically/#restart-policy-details

> A restart policy only takes effect after a container starts successfully. In this case, starting successfully means that the container is up for at least 10 seconds and Docker has started monitoring it. This prevents a container which does not start at all from going into a restart loop.
