### PR TITLE
Poll lamps with Philips, Atmel, Gledopto, Mueller-Licht manufacturer codes

### LINKED ISSUE #4969: Group state is not updating in Home Assistant
## What happened

I have 2 Philips lamps (Hue Lux A19 bulb E27) in a group (KidsCornerGroup) and an Ikea Tradfri E1743 button (KidsCornerSwitch) binded to it.

image

image

When I turn on the lights with the KidsCornerSwitch, Home Assistant does not show the group as on.

## What did you expect to happen

Home Assistant should show the group is on if I use the KidsCornerSwitch to turn it on.

## How to reproduce it (minimal and precise)

Home assistant relevant config:

```yaml
lights:
- platform: mqtt
  schema: json
  name: Kids Corner
  command_topic: "zigbee2mqtt/KidsCornerGroup/set"
  state_topic: "zigbee2mqtt/KidsCornerGroup"
  brightness: true
```

## Debug info
Zigbee2MQTT version: 1.16.1
Adapter hardware: CC26X2R1
Adapter firmware version: 20201026

Logs:

```txt
INFO: MQTT publish: topic 'zigbee2mqtt/KidsCornerSwitch', payload '{"action":"on","battery":87,"click":"on","linkquality":57,"update":{"state":"idle"},"update_available":false}'
INFO: MQTT publish: topic 'zigbee2mqtt/KidsCornerSwitch', payload '{"action":"","battery":87,"linkquality":57,"update":{"state":"idle"},"update_available":false}'
INFO: MQTT publish: topic 'zigbee2mqtt/KidsCornerSwitch', payload '{"battery":87,"click":"","linkquality":57,"update":{"state":"idle"},"update_available":false}'
INFO: MQTT publish: topic 'zigbee2mqtt/KidsCornerSwitch/action', payload 'on'
INFO: MQTT publish: topic 'zigbee2mqtt/KidsCornerSwitch/click', payload 'on'
INFO: MQTT publish: topic 'zigbee2mqtt/KidsCornerSwitch', payload '{"action":"off","battery":87,"click":"off","linkquality":66,"update":{"state":"idle"},"update_available":false}'
INFO: MQTT publish: topic 'zigbee2mqtt/KidsCornerSwitch', payload '{"action":"","battery":87,"linkquality":66,"update":{"state":"idle"},"update_available":false}'
INFO: MQTT publish: topic 'zigbee2mqtt/KidsCornerSwitch', payload '{"battery":87,"click":"","linkquality":66,"update":{"state":"idle"},"update_available":false}'
INFO: MQTT publish: topic 'zigbee2mqtt/KidsCornerSwitch/action', payload 'off'
INFO: MQTT publish: topic 'zigbee2mqtt/KidsCornerSwitch/click', payload 'off'
```

### PR DESCRIPTION
**Pull request by pedrolamas**
This fixes #4969 by checking for both Philips and Atmel manufacturer codes (as we came to realize that Philips Hue lamps have components from both)

### CODE REVIEW

File: lib/extension/report.js [hunk 1]
```diff
@@ -82,7 +82,10 @@ const pollOnMessage = [
         // Read the following attributes
         read: {cluster: 'genLevelCtrl', attributes: ['currentLevel']},
         // When the bound devices/members of group have the following manufacturerID
-        manufacturerID: ZigbeeHerdsman.Zcl.ManufacturerCode.Philips,
+        manufacturerIDs: [
+            ZigbeeHerdsman.Zcl.ManufacturerCode.Philips,
+            ZigbeeHerdsman.Zcl.ManufacturerCode.ATMEL,
```
Comment (sjorge) [inline lib/extension/report.js:87]: I guess we should also add GLEDOPTO_CO_LTD here, as they also don't support reporting.

**Comment by sjorge** [comment]
LGTM

File: lib/extension/report.js (hunk 1 above)
Comment (pedrolamas) [reply lib/extension/report.js:87]: [This table](https://www.zigbee2mqtt.io/information/report.html#support) seems to indicate that GLEDOPTO_CO_LTD and MUELLER_LICHT_INT are not reporting, so maybe add both then?

Comment (pedrolamas) [reply lib/extension/report.js:87]: Done, added both!

Comment (sjorge) [reply lib/extension/report.js:87]: Ah yes, good catch. I tested Mueller a bit after Gledopto and forgot about them. (I was not impressed with either tbh)

**Comment by Koenkk** [comment]
Thanks again @pedrolamas ! :smile:
