### PR TITLE
Home Assistant: set unknown values to null #6987

### LINKED ISSUE #6987: Template rendering warnings in latest Home Assistant beta for dictionary missing attribute
## What happened

Starting in Home Assistant `2021.4.0` templates referencing an attribute of a dictionary which does not exist generate a warnings like this:

```
2021-04-07 15:05:31 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'
```

I traced these errors back to the source and its a result of the discovery payload sent by Z2M to Home Assistant. The discovery payload sends this as the template to use to parse the value for a sensor out of the JSON payload:

```
value_template: '{{ value_json.action }}'
```

For devices which don't report all their attributes all the time (ex. remotes that report an action on button press) this creates a problem. Anytime a payload is received without the attribute a warning is created. This warning will become an error and a failure starting in `2021.10` (see https://github.com/home-assistant/core/pull/48140 ) 

Fortunately there appears to be a relatively easy fix. If the discovery template is changed to this then all the errors should go away:

```
{{ value_json.action | default('', true) }}
```

It's a bit strange to always default to `''` even for numeric attributes but this is what was occurring before. Returning `None` as the default also works and does not generate a warning (I tested). That might be more correct but not sure if that has any other consequences downstream. The `true` is so it only appllies the default if things truly don't exist and not just if they evaluate to `false` (see [default](https://jinja.palletsprojects.com/en/master/templates/#default)).

## What did you expect to happen

Not to see a warning for attribute did not exist

## How to reproduce it (minimal and precise)

The error above is showing what can occur if you have a remote type device such as [Philips 929002398602](https://www.zigbee2mqtt.io/devices/929002398602.html) that checks in all the time with basic attributes like battery and linkquality and includes an action on button press. You can also create an error like this with any device by doing the following:

1. Proceed with Home Assistant discovery for the device
2. Use `filtered_attributes` to tell Z2M to stop reporting one or more attributes
3. See you get warnings for the sensors trying to read an attribute that is no longer being reported in

This creates errors like this:

```
2021-04-06 21:24:44 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: dict object has no attribute voltage
```

I realize in this particular use case the right fix is just to disable the sensor in Home Assistant (which is what I did). But I don't know all the devices that report some attributes occaisionally, figured it would be good to have a way to simulate that with any device.

## Debug info
Zigbee2MQTT version: 1.18.2
Home Assistant version: 2021.4.0b5
Adapter hardware: Conbee II
Adapter firmware version: 0x264a0700

### PR DESCRIPTION
**Pull request by Koenkk**
Fixes #6987
Alternative for https://github.com/Koenkk/zigbee2mqtt/pull/6988

Home Assistant 2021.4 => throws warnings when values are missing from the state. This PR sets all unknown values to null.

E.g. given that we have a temperature/humidity sensor where the humidity and temperature is unknown yet. Next the sensor reports the temperature so `{"temperature": 20}` is published. Now HA will generate a warning that the `humidity` property is missing. With this pr `{"temperature": 20, "humidity": null}` would be published.

@mdegat01 @frenck can you take a look at this?

### CODE REVIEW

**Comment by frenck** [comment]
I'll pull this in and run it a bit, see what happens.

**Review by frenck — APPROVED** [review]
To me this makes sense ✅ 

If there are still error cases left now, it probably is a different issue 👍

**Comment by mdegat01** [comment]
So essentially if a message is received with partial state from the device it fills in the missing fields it was expecting with `null` before publishing to HA. Yea that sounds good to me. I believe this would address the use cases raised in the original issue and the other PR. Passing back `null` to HA will trigger a state change but I think that's desired since the current state is in fact none.

Thanks for the quick turnaround @Koenkk . Sorry for causing drama with the other PR.

**Comment by frenck** [comment]
> Sorry for causing drama with the other PR.

I don't think you need to excuse for that. It was a good discussion with a lot of insight and different takes on the story. That usually results in the best outcome 👍

**Comment by Koenkk** [comment]
@frenck thanks for the feedback

@mdegat01 agree with @frenck , this was good to start the discussion with.

@frenck something that I'm not 100% confident of. For e.g. a light it will only set the `state` to `null`. I noticed HA doesn't throw any warnings when e.g. brightness or color temp is missing from the payload, is this expected?

File: lib/controller.js [hunk 1]
```diff
@@ -334,6 +334,12 @@ class Controller {
             resolvedEntity.settings.filtered_attributes.forEach((a) => delete messagePayload[a]);
         }
 
+        for (const extension of this.extensions) {
+            if (extension.adjustMessagePayloadBeforePublish) {
+                extension.adjustMessagePayloadBeforePublish(resolvedEntity, messagePayload);
```
Comment (sjorge) [inline lib/controller.js:339]: @Koenkk in theory we could use this to copy color.hue -> color.h and color.saturation -> color.s too to make ha happy?

**Comment by frenck** [comment]
> @frenck something that I'm not 100% confident of. For e.g. a light it will only set the state to null. I noticed HA doesn't throw any warnings when e.g. brightness or color temp is missing from the payload, is this expected?

I would say that is expected. Light are a bit special due to Home Assistant history (light are originally solely based on Hue, as that is how Home Assistant started).

A Home Assistant light entity does not expose its state attributes when the state of the light is not "on". The original idea behind it is: "Well, if a light is off, you can't walk to it and visually confirm it is 50% brightness". Thus, lights do not have a brightness when not "on".

This is only true for lights, personal opinions aside (I think it is stupid), this is how it is and probably the reason why it doesn't blow up in those cases?

File: lib/controller.js (hunk 1 above)
Comment (Koenkk) [reply lib/controller.js:339]: Yes! Good idea 👍

**Comment by Koenkk** [comment]
@mdegat01 could you also test this PR on your side to make sure no warnings are thrown anymore?

**Comment by mdegat01** [comment]
@Koenkk yep, pulled it in, works great. I undisabled some of the sensors for attributes I was filtering out and they just get state `None`, no warnings.

Also noticed I was actually had a ton of warnings prior to this about missing `linkquality` from sensors. Not sure when that started as I didn't notice it initially but those are all gone now too. LGTM

File: lib/controller.js (hunk 1 above)
Comment (sjorge) [reply lib/controller.js:339]: Someone who uses HA should look into it, as I have no way to test this. (As I do not use HA)

**Comment by juslex** [comment]
I upgraded to the latest dev version 1.18.2-dev commit: 07262bd6, but I am receiving this erros messages:

021-04-13 09:16:01 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'INFO' when rendering '{{ value_json['INFO'].VERSION}}'
2021-04-13 09:16:02 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'INFO' when rendering '{{ value_json['INFO'].VERSION}}'
2021-04-13 09:16:03 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'INFO' when rendering '{{ value_json['INFO'].VERSION}}'
2021-04-13 09:16:04 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'INFO' when rendering '{{ value_json['INFO'].VERSION}}'
2021-04-13 09:16:05 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'INFO' when rendering '{{ value_json['INFO'].VERSION}}'

**Comment by frenck** [comment]
Are you sure that that is z2m related? I'm not extremely familiar with the z2m codebase yet but could find a direct reference for that.

**Comment by juslex** [comment]
it can be the z2m or local-tuya I have 3 covers there.  how do i find out?

**Comment by frenck** [comment]
Check your templates, or, in case they are pushed in via MQTT, look at the contents of your broker to determine which device/software brings in that template

**Comment by Koenkk** [comment]
`{{ value_json['INFO'].VERSION}}` is definitely not Z2M

**Comment by towerhand** [comment]
`2021-04-13 11:33:51 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'`

`2021-04-13 11:33:51 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'value' when rendering '{{ value_json.value}}'`

`2021-04-13 12:27:22 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'value' when rendering '{{ {}[value_json.value] | default(value_json.value) }}'`

Not sure if related to z2m but I still have this 3 kinds of warnings. Should I create a separate issue?

**Comment by Koenkk** [comment]
@towerhand click is deprecated therefore not initialised to null (read e.g. https://www.zigbee2mqtt.io/devices/E1743.html#deprecated-click-event). Don't know about the other, unclear if they come from z2m or not.

**Comment by towerhand** [comment]
Thanks, took care of that, got confused and thought the `legacy_api: false` in the advance settings took care of that too.

**Comment by ssiergl** [comment]
just to confirm.....using around 70 devices different kind and manufactures....this patch works well...no template warnings in home assistant core log

thanks :)

**Comment by tanus10** [comment]
> @towerhand click is deprecated therefore not initialised to null (read e.g. https://www.zigbee2mqtt.io/devices/E1743.html#deprecated-click-event). Don't know about the other, unclear if they come from z2m or not.

Do we need to add 
```
    legacy: false
```
to every "click" event publishing switches? (I added it to all 9 Xiaomi wireless switches)

**Comment by juslex** [comment]
> `{{ value_json['INFO'].VERSION}}` is definitely not Z2M



> Are you sure that that is z2m related? I'm not extremely familiar with the z2m codebase yet but could find a direct reference for that. And not seeing those errors on my end.

I confirm it is not from z2m. also not from the tuya local, I removed this integration and the error continued to appear. How do I find out the causer, is it on the mqtt bridge?

**Comment by 3gyptian** [comment]
Applied latest dev branch and it resolved many of my HA warnings like these ones:
```
2021-04-17 11:16:15 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'keypad_lockout' when rendering '{{ value_json.keypad_lockout }}'
2021-04-17 11:16:15 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'current' when rendering '{{ value_json.current }}'
2021-04-17 11:16:15 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'voltage' when rendering '{{ value_json.voltage }}'
2021-04-17 11:17:06 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'power' when rendering '{{ value_json.power }}'
2021-04-17 11:17:06 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'energy' when rendering '{{ value_json.energy }}'
```

However, I'm still seeing these come through:

```
2021-04-17 13:01:25 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: dict object has no element Undefined when rendering '{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}'
2021-04-17 13:02:37 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: dict object has no element Undefined when rendering '{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}'
2021-04-17 13:02:43 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: dict object has no element Undefined when rendering '{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}'
```

Which match t he timestamps match the zigbee2mqtt logs:

```
Apr 17 13:01:25 raspiesp2 npm[25335]: #033[32mZigbee2MQTT:info #033[39m 2021-04-17 13:01:25: MQTT publish: topic 'zigbee2mqtt/livingroom_thermostat', payload '{"current":null,"energy":null,"keypad_lockout":null,"linkquality":13,"local_temperature":23.31,"occupied_heating_setpoint":21,"operation":"idle","pi_heating_demand":0,"power":null,"system_mode":"heat","voltage":null}'
Apr 17 13:02:37 raspiesp2 npm[25335]: #033[32mZigbee2MQTT:info #033[39m 2021-04-17 13:02:37: MQTT publish: topic 'zigbee2mqtt/bedroom_thermostat', payload '{"current":null,"energy":null,"keypad_lockout":null,"linkquality":13,"local_temperature":22.81,"occupied_heating_setpoint":20.5,"operation":"idle","pi_heating_demand":0,"power":null,"system_mode":"heat","voltage":null}'
Apr 17 13:02:43 raspiesp2 npm[25335]: #033[32mZigbee2MQTT:info #033[39m 2021-04-17 13:02:43: MQTT publish: topic 'zigbee2mqtt/bedroom_thermostat', payload '{"current":null,"energy":null,"keypad_lockout":null,"linkquality":13,"local_temperature":23.01,"occupied_heating_setpoint":20.5,"operation":"idle","pi_heating_demand":0,"power":null,"system_mode":"heat","voltage":null}'
```

Ideas anyone?

**Comment by derekoharrow** [comment]
I'm running the latest Dev docker image (latest-dev), and am still getting some warnings:

`2021-04-19 10:39:15 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'`

This is for a Xiaomi Aqara button. 

When I click or double-click it it produces this same error relating to .click.

**Comment by frenck** [comment]
@derekoharrow See response on that here: <https://github.com/Koenkk/zigbee2mqtt/pull/7032#issuecomment-818956134>

**Comment by derekoharrow** [comment]
> Just to be sure, you need to change all .click statement in the automations.yaml to .action.
> Xiaomi switches have two different ways to detect state and I saw I configured a couple of switches with .click (or was it _click) which produced remaining warnings.
> 
> Be sure to search for .click or _click in the automations and scripts.

This isn't to do with the HA automations, it's the Z2M config. As pointed out by @frenck above, you need to turn off the legacy_api mode for the devices that issue a click and action event.

**Comment by tanus10** [comment]
@derekoharrow 

and sensors.yaml too.

Please refer bellow link.
[Link](https://www.zigbee2mqtt.io/devices/WXKG01LM.html#manual-home-assistant-configuration)

**Comment by bachoo786** [comment]
I am having the same problem as @mdegat01 @juslex  my Homeassistant keeps on throwing errors and piling up my logs. Here is my log and I think its from Z2M from the tuya thermostat that I am using.

```
2021-04-21 15:48:26 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'valve_detection' when rendering '{{ value_json.valve_detection }}'
2021-04-21 15:48:26 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: dict object has no element Undefined when rendering '{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}'
2021-04-21 15:48:31 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'max_temperature' when rendering '{{ value_json.max_temperature }}'
2021-04-21 15:48:31 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'min_temperature' when rendering '{{ value_json.min_temperature }}'
2021-04-21 15:48:31 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'valve_detection' when rendering '{{ value_json.valve_detection }}'
2021-04-21 15:48:32 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: dict object has no element Undefined when rendering '{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}'
2021-04-21 15:48:42 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'max_temperature' when rendering '{{ value_json.max_temperature }}'
2021-04-21 15:48:42 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'min_temperature' when rendering '{{ value_json.min_temperature }}'
2021-04-21 15:48:42 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'valve_detection' when rendering '{{ value_json.valve_detection }}'
2021-04-21 15:48:42 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: dict object has no element Undefined when rendering '{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}'
```
I checked if I could add legacy : false for the TuYa TS0601_thermostat configuration in Z2M but there is no such thing in the documentation (link: https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html).

Can anyone help please as my HA logs are going crazy. CC: @Koenkk, @frenck

**Comment by mdegat01** [comment]
@bachoo786 This PR is merged and looking at what you're seeing it should fix about 75% of those.

```
2021-04-21 15:48:31 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'max_temperature' when rendering '{{ value_json.max_temperature }}'
2021-04-21 15:48:31 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'min_temperature' when rendering '{{ value_json.min_temperature }}'
2021-04-21 15:48:31 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'valve_detection' when rendering '{{ value_json.valve_detection }}'
```
These 3 are what the PR was targeting. In the latest builds of Z2M the JSON payload should include fields for `max_temperature`, `min_temperature` and `valve_detection` with the value set to `null` when Z2M gets an update from that device which does not include data for those fields. It sounds like those sensors will be `unavailable/unknown` a lot but you won't see an error, you'll have to decide if that's the behavior you were expecting or if that means something else is wrong.

```
2021-04-21 15:48:32 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: dict object has no element Undefined when rendering '{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}'
```

This PR won't fix this one. What will happen is the JSON payload will now include `"running_state": null` when it gets a state change event from the device that doesn't data on `running_state`. But as you can see from that template its then going to try and find a field in `values` with a key of `null` and obviously that does not exist. So then you will get a dict object undefined error.

Is this device behaving correctly? I don't really know this device `running_state` sounds like a pretty fundamental attribute of a thermostat. It doesn't seem like it should be possible for it to report in without specifying a `running_state` if it is actually running. But I think Koenkk will have to weigh in here as I don't know enough about the details other then to identify it as a potential issue even after this PR.

Also just an FYI @bachoo786 this PR is merged to the `dev` branch of Z2M. Assuming you are running the stable branch of the Z2M addon in HA that means you will continue to see the warnings until the following occurs:
1) A new version of Z2M (this repo) is released - May 1st (estimate)
2) The Z2M addon updates its stable version to point to the new stable version of Z2M - unknown timeline but usually occurs pretty quickly after a new Z2M release comes out, probably a couple days after May 1st

If you want to speed up that timeline then you can switch to the `dev`/`edge` version of the Z2M add-on as that tracks the `dev` branch in Z2M and the change has already been merged there. If you don't want to do that then you'll have to tolerate the warnings until at least May 1st. Would suggest increasing the level for the `homeassistant.helpers.template` logger to `error` after you feel confident you've resolved any other issues it has identified with troublesome templates.

**Comment by bachoo786** [comment]
> @bachoo786 This PR is merged and looking at what you're seeing it should fix about 75% of those.
> 
> ```
> 2021-04-21 15:48:31 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'max_temperature' when rendering '{{ value_json.max_temperature }}'
> 2021-04-21 15:48:31 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'min_temperature' when rendering '{{ value_json.min_temperature }}'
> 2021-04-21 15:48:31 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'valve_detection' when rendering '{{ value_json.valve_detection }}'
> ```
> 
> These 3 are what the PR was targeting. In the latest builds of Z2M the JSON payload should include fields for `max_temperature`, `min_temperature` and `valve_detection` with the value set to `null` when Z2M gets an update from that device which does not include data for those fields. It sounds like those sensors will be `unavailable/unknown` a lot but you won't see an error, you'll have to decide if that's the behavior you were expecting or if that means something else is wrong.
> 
> ```
> 2021-04-21 15:48:32 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: dict object has no element Undefined when rendering '{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}'
> ```
> 
> This PR won't fix this one. What will happen is the JSON payload will now include `"running_state": null` when it gets a state change event from the device that doesn't include data on `running_state`. But as you can see from that template its then going to try and find a field in `values` with a key of `null` and obviously that does not exist. So then you will get a dict object has no element warning.
> 
> Is this device behaving correctly? I don't really know this device but `running_state` sounds like a pretty fundamental attribute of a thermostat. It doesn't seem like it should be possible for it to report in without specifying a `running_state` if it is actually running. But I think Koenkk will have to weigh in here as I don't know enough about the details other then to identify it as a potential issue even after this PR.
> 
> Also just an FYI @bachoo786 this PR is merged to the `dev` branch of Z2M. Assuming you are running the stable branch of the Z2M addon in HA that means you will continue to see the warnings until the following occurs:
> 
> 1. A new version of Z2M (this repo) is released - May 1st (estimate)
> 2. The Z2M addon updates its stable version to point to the new stable version of Z2M - unknown timeline but usually occurs pretty quickly after a new Z2M release comes out, probably a couple days after May 1st
> 
> If you want to speed up that timeline then you can switch to the `dev`/`edge` version of the Z2M add-on as that tracks the `dev` branch in Z2M and the change has already been merged there. If you don't want to do that then you'll have to tolerate the warnings until at least May 1st. Would suggest increasing the level for the `homeassistant.helpers.template` logger to `error` after you feel confident you've resolved any other issues it has identified with troublesome templates.

Hi @mdegat01 thanks for the detailed explanation. The device is behaving correctly only for these errors/warnings.

I guess I will wait till the 1st of May for the release of the latest Z2M, hoping the issues stated in my previous post are sorted out. 

One thing, how do I increase the level for the homeassistant.helpers.template logger to error?

**Comment by mdegat01** [comment]
@bachoo786 see [logger](https://www.home-assistant.io/integrations/logger/). The component is `homeassistant.helpers.template` so add it under `logs` as shown in the example. You can also fix it immediately without restarting HA by changing the logging level of that component on the fly using [logger.set_level](https://www.home-assistant.io/integrations/logger/#service-set_level)

**Comment by wsw70** [comment]
> This PR is merged and looking at what you're seeing it should fix about 75% of those.

If this helps, I still have the issues with  1.21.1 (commit: eb5750d)

    2021-09-06 12:26:56 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'

**Comment by Koenkk** [comment]
click is deprecated, see e.g. https://www.zigbee2mqtt.io/devices/WXKG01LM.html#deprecated-click-event how to disable it.

**Comment by quadhammer** [comment]
I've disabled that click feature, with the legacy option, but because my Xiaomi Temp Sensor (https://www.zigbee2mqtt.io/devices/WSDCGQ11LM.html#xiaomi-wsdcgq11lm) has 'N/A' for its link quality, I get the error in the logs:

Logger: homeassistant.helpers.template
Source: helpers/template.py:1822
First occurred: 3:01:14 PM (1 occurrences)
Last logged: 3:01:14 PM

Template variable warning: 'dict object' has no attribute 'linkquality' when rendering '{{ value_json.linkquality }}'

Is there a way to either generate a linkquality number, or fix the error?

Thank you

**Comment by buhito81** [comment]
Having the same issue:

`2022-09-16 13:38:33MQTT publish: topic 'zigbee2mqtt/Bedroom Curtain Left', payload '{"action":null,"battery":100,"charging":false,"device_temperature":23,"hooks_state":"unlocked","linkquality":255,"motor_state":null,"position":86,"power_outage_count":2,"power_source":"battery","running":false,"state":"OPEN","target_position":72,"update":{"progress":13.04,"remaining":1613,"state":"updating"},"update_available":false,"voltage":3000}'`

With the https://www.zigbee2mqtt.io/devices/ZNCLBL01LM.html#xiaomi-znclbl01lm
