### PR TITLE
fix: generate group ID if empty string given

### LINKED ISSUE #27698: When adding a zigbee group in the gui with no group number it saves to configuration.yaml with an empty group number and breaks the config
### What happened?

When adding a zigbee group in the gui with no group number it saves to configuration.yaml with an empty group number and breaks the config.

I'm using the new windfront gui if that matters - here's images of what the configuration.yaml file showed and what the z2m logs in the haos addon showed.

Image

Image

### What did you expect to happen?

not to break lol

### How to reproduce it (minimal and precise)

create group with no group id and see an error in the gui but it then creates the entry in the configuration.yaml with no group number and breaks the config.

### Zigbee2MQTT version

2.4.0-1

### Adapter firmware version

20240710

### Adapter

Tube cc2652p7 PoE coordinator

### Setup

addon on home assistant os on n100 mini pc.

### Debug log

_No response_

### PR DESCRIPTION
**Pull request by Nerivec**
Fixes #27698

### CODE REVIEW

File: lib/util/settings.ts [hunk 1]
```diff
@@ -596,7 +596,7 @@ export function addGroup(name: string, id?: string): GroupOptions {
         settings.groups = {};
     }
 
-    if (id == null) {
+    if (id == null || id === "") {
```
Comment (Koenkk) [inline lib/util/settings.ts]:
```suggestion
    if (id == null || id.trim() === "") {
```

**Comment by Koenkk** [comment]
Thanks!
